import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Legal pages are generated by legal/build.py into web/content/legal/<country>/.
 * Both countries are loaded; pages pick the collection for SITE_COUNTRY.
 */
const schema = z.object({
  title: z.string(),
  slug: z.string(),
  version: z.string(),
  last_updated: z.coerce.date(),
  country: z.enum(['usa', 'india']),
  app_name: z.string(),
  company: z.string(),
  canonical: z.string(),
  order: z.number(),
  generated: z.boolean().optional(),
});

const legal = (c: 'usa' | 'india') =>
  defineCollection({ loader: glob({ pattern: '*.md', base: `../content/legal/${c}` }), schema });

export const collections = { legal_usa: legal('usa'), legal_india: legal('india') };
