#!/usr/bin/env ruby
# Creates the iOS build configurations and shared schemes for the six flavors
# (usaDev, usaStaging, usaProd, indiaDev, indiaStaging, indiaProd).
#
# Flutter expects, for `flutter build ios --flavor usaProd`:
#   - a shared scheme named usaProd
#   - build configurations Debug-usaProd, Release-usaProd, Profile-usaProd
#
# Idempotent: re-running updates settings without duplicating anything.
#   gem install xcodeproj && ruby tool/ios/setup_flavors.rb
require "xcodeproj"
require "fileutils"

ROOT = File.expand_path("../..", __dir__)
PROJECT_PATH = File.join(ROOT, "ios", "Runner.xcodeproj")
FLAVOR_DIR = File.join(ROOT, "ios", "Flutter", "flavors")

COUNTRIES = {
  "usa"   => { bundle: "com.calecute.iwant.usa",   name: "I Want USA",   host: "iwantusa.app" },
  "india" => { bundle: "com.calecute.iwant.india", name: "I Want India", host: "iwantindia.app" },
}.freeze
ENVS = {
  "dev"     => { suffix: ".dev", label: " Dev" },
  "staging" => { suffix: ".stg", label: " Beta" },
  "prod"    => { suffix: "",     label: "" },
}.freeze
BUILD_TYPES = { "Debug" => :debug, "Profile" => :release, "Release" => :release }.freeze

FileUtils.mkdir_p(FLAVOR_DIR)
project = Xcodeproj::Project.open(PROJECT_PATH)
runner = project.targets.find { |t| t.name == "Runner" } or abort("Runner target missing")
flavors = []

COUNTRIES.each do |country, c|
  ENVS.each do |env, e|
    flavor = "#{country}#{env.capitalize}"
    flavors << flavor
    BUILD_TYPES.each do |type, kind|
      config_name = "#{type}-#{flavor}"
      xcconfig_rel = "Flutter/flavors/#{config_name}.xcconfig"
      File.write(File.join(ROOT, "ios", xcconfig_rel), <<~XC)
        // Generated by tool/ios/setup_flavors.rb. Edit the script, not this file.
        #include? "../../Pods/Target Support Files/Pods-Runner/Pods-Runner.#{config_name.downcase}.xcconfig"
        #include "../#{type == 'Debug' ? 'Debug' : 'Release'}.xcconfig"
        // Optional, untracked per-developer/CI overrides (Google client ids etc.).
        #include? "../secrets/#{flavor}.xcconfig"
        PRODUCT_BUNDLE_IDENTIFIER = #{c[:bundle]}#{e[:suffix]}
        APP_DISPLAY_NAME = #{c[:name]}#{e[:label]}
        DEEP_LINK_HOST = #{c[:host]}
        IWANT_FLAVOR = #{flavor}
        FLUTTER_TARGET = lib/main_#{country}.dart
        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-#{flavor}
      XC

      file_ref = project.files.find { |f| f.path == xcconfig_rel } ||
                 project.main_group.new_file(xcconfig_rel)
      base = kind == :debug ? "Debug" : (type == "Profile" ? "Profile" : "Release")

      [project, runner].each do |owner|
        list = owner.build_configuration_list
        cfg = list[config_name]
        unless cfg
          template = list[base] or abort("#{base} configuration missing on #{owner}")
          cfg = project.new(Xcodeproj::Project::Object::XCBuildConfiguration)
          cfg.name = config_name
          cfg.build_settings = Marshal.load(Marshal.dump(template.build_settings))
          list.build_configurations << cfg
        end
        next unless owner.equal?(runner)
        cfg.base_configuration_reference = file_ref
        bs = cfg.build_settings
        bs.delete("PRODUCT_BUNDLE_IDENTIFIER") # comes from the xcconfig
        bs["CODE_SIGN_ENTITLEMENTS"] = "Runner/Runner.entitlements"
        bs["ASSETCATALOG_COMPILER_APPICON_NAME"] = "$(ASSETCATALOG_COMPILER_APPICON_NAME)"
      end
    end
  end
end

# Copy the flavor's GoogleService-Info.plist (untracked) into the bundle when present.
phase_name = "Copy GoogleService-Info.plist for flavor"
unless runner.shell_script_build_phases.any? { |p| p.name == phase_name }
  phase = runner.new_shell_script_build_phase(phase_name)
  phase.shell_script = <<~SH
    SRC="${PROJECT_DIR}/config/${IWANT_FLAVOR}/GoogleService-Info.plist"
    DST="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
    if [ -f "$SRC" ]; then cp "$SRC" "$DST"; else echo "warning: $SRC missing; Firebase disabled for ${IWANT_FLAVOR}"; fi
  SH
  runner.build_phases.move(phase, runner.build_phases.index(runner.resources_build_phase) + 1)
end

# PrivacyInfo.xcprivacy and entitlements live in Runner/.
runner_group = project.main_group.find_subpath("Runner", false)
%w[PrivacyInfo.xcprivacy Runner.entitlements].each do |name|
  next if runner_group.files.any? { |f| f.path == name }
  ref = runner_group.new_file(name)
  runner.resources_build_phase.add_file_reference(ref) if name.end_with?(".xcprivacy")
end
project.save

# One shared scheme per flavor, mirroring Runner.xcscheme.
template_scheme = File.join(PROJECT_PATH, "xcshareddata", "xcschemes", "Runner.xcscheme")
flavors.each do |flavor|
  scheme = Xcodeproj::XCScheme.new(template_scheme)
  scheme.launch_action.build_configuration = "Debug-#{flavor}"
  scheme.test_action.build_configuration = "Debug-#{flavor}"
  scheme.analyze_action.build_configuration = "Debug-#{flavor}"
  scheme.profile_action.build_configuration = "Profile-#{flavor}"
  scheme.archive_action.build_configuration = "Release-#{flavor}"
  scheme.save_as(PROJECT_PATH, flavor, true)
end
puts "Configured #{flavors.size} flavors: #{flavors.join(', ')}"
