include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/l10n/gen/**
    - web/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
