-- 0300 Core tables (Section 6). Identical schema in both country projects.
-- Money = *_minor bigint + currency char(3). Every table: created_at,
-- updated_at (trigger) and RLS enabled (policies in 0600).
set search_path = public, extensions;

-- profiles ---------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  phone text,
  email text,
  photo_url text,
  language text not null default 'en',
  roles text[] not null default '{buyer}'
    check (roles <@ array['buyer','seller','admin']::text[]),
  active_mode text not null default 'buyer' check (active_mode in ('buyer','seller')),
  status text not null default 'active' check (status in ('active','suspended','banned','deleted')),
  suspended_until timestamptz,
  status_reason text,
  timezone text,
  notification_prefs jsonb not null default
    '{"mode":"instant","quiet_hours":{"start":"22:00","end":"07:00"},"push":true,"marketing":false}'::jsonb,
  is_review_account boolean not null default false,
  referral_code text unique default substr(md5(gen_random_uuid()::text), 1, 8),
  referred_by uuid references public.profiles(id) on delete set null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- addresses --------------------------------------------------------------------
create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text,
  line1 text not null,
  line2 text,
  city text,
  state text,
  postal_code text,
  location geography(Point, 4326),
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- device_tokens ----------------------------------------------------------------
create table public.device_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  fcm_token text not null unique,
  platform text not null check (platform in ('android','ios','web')),
  app_version text,
  locale text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- blocks -----------------------------------------------------------------------
create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

-- postal_codes / cities ----------------------------------------------------------
create table public.postal_codes (
  code text primary key,
  centroid geography(Point, 4326),
  city text,
  district text,
  state text,
  state_code text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cities (
  id bigint generated by default as identity primary key,
  geoname_id bigint unique,
  name text not null,
  ascii_name text,
  slug text,
  state text,
  state_code text,
  population bigint,
  centroid geography(Point, 4326),
  timezone text,
  priority int, -- lower = processed first by outreach; null = normal
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- categories --------------------------------------------------------------------
create table public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete restrict,
  slug text not null unique,
  names jsonb not null check (jsonb_typeof(names) = 'object' and names ? 'en'),
  policy text not null default 'allowed' check (policy in ('allowed','restricted','blocked')),
  required_licence_type text,
  disclaimer jsonb,
  policy_reason jsonb, -- localized explanation shown when blocked/restricted
  field_schema jsonb,
  keywords text[] not null default '{}',
  icon text,
  sort int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (policy <> 'restricted' or required_licence_type is not null)
);

-- Keyword classifier for blocked / restricted content (keywords now, ML later).
create table public.category_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null,
  lang text not null default 'en',
  category_id bigint references public.categories(id) on delete cascade,
  action text not null check (action in ('block','suggest')),
  reason jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (keyword, lang, action)
);

-- sellers ------------------------------------------------------------------------
create table public.sellers (
  id uuid primary key references public.profiles(id) on delete cascade,
  business_name text not null check (length(trim(business_name)) between 2 and 120),
  slug text unique,
  logo_url text,
  photos text[] not null default '{}',
  description text,
  years_in_business int check (years_in_business between 0 and 200),
  brands text[] not null default '{}',
  area_type text not null default 'radius' check (area_type in ('radius','codes','nationwide')),
  center geography(Point, 4326),
  radius_km numeric(6,1) check (radius_km is null or radius_km between 0.5 and 500),
  service_codes text[] not null default '{}',
  city text,
  state text,
  timezone text,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified','pending','verified','rejected')),
  verified_at timestamptz,
  rating_avg numeric(3,2) not null default 0,
  rating_count int not null default 0,
  quotes_sent int not null default 0,
  quotes_won int not null default 0,
  avg_response_mins int,
  early_partner boolean not null default false,
  free_until timestamptz,
  notify_mode text not null default 'instant' check (notify_mode in ('instant','hourly','daily')),
  quiet_hours_start time default '22:00',
  quiet_hours_end time default '07:00',
  featured_until timestamptz,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (area_type <> 'radius' or (center is not null and radius_km is not null)),
  check (area_type <> 'codes' or cardinality(service_codes) > 0)
);

-- Seller contact details: revealed only to the seller, admins and buyers who
-- accepted one of the seller's quotes (Section 2.3 privacy by default).
create table public.seller_contacts (
  seller_id uuid primary key references public.sellers(id) on delete cascade,
  business_phone text,
  business_email text,
  website text,
  address_line text,
  postal_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.seller_categories (
  seller_id uuid not null references public.sellers(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (seller_id, category_id)
);

create table public.seller_documents (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.sellers(id) on delete cascade,
  doc_type text not null check (doc_type in
    ('gstin','udyam','pan','shop_photo','ein','state_license','business_address','website','other')),
  doc_number text,
  file_path text, -- verification-docs bucket: {seller_id}/...
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.seller_licences (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.sellers(id) on delete cascade,
  licence_type text not null,
  number text not null,
  issuer text,
  state text,
  category_ids bigint[] not null default '{}',
  file_path text,
  expires_at timestamptz,
  status text not null default 'pending' check (status in ('pending','approved','rejected','expired')),
  rejection_reason text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  expiry_warned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- entitlements (seller plans from Play, Apple, Stripe, Razorpay, admin grants) -----
create table public.entitlements (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.sellers(id) on delete cascade,
  store text not null check (store in ('play','apple','web','manual')),
  provider text check (provider in ('google_play','app_store','stripe','razorpay','admin')),
  product_id text not null,
  tier text not null check (tier in ('pro','credits')),
  status text not null default 'active'
    check (status in ('pending','active','grace','on_hold','paused','cancelled','expired','revoked','refunded')),
  credits_balance int not null default 0 check (credits_balance >= 0),
  renews_at timestamptz,
  expires_at timestamptz,
  original_transaction_id text,
  external_customer_id text,
  last_event_at timestamptz,
  raw jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index entitlements_store_txn_uidx
  on public.entitlements (store, original_transaction_id) where original_transaction_id is not null;

-- Idempotency log for store / payment webhooks.
create table public.billing_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  event_type text,
  seller_id uuid references public.sellers(id) on delete set null,
  payload jsonb,
  processed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, event_id)
);

-- requests -------------------------------------------------------------------------
create table public.requests (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint not null references public.categories(id),
  title text not null check (length(trim(title)) between 3 and 140),
  description text check (description is null or length(description) <= 4000),
  fields jsonb not null default '{}'::jsonb,
  budget_min_minor bigint check (budget_min_minor is null or budget_min_minor >= 0),
  budget_max_minor bigint check (budget_max_minor is null or budget_max_minor >= 0),
  currency char(3) not null,
  budget_visible boolean not null default true,
  needed_by date,
  location geography(Point, 4326), -- coarse point (~110 m); exact pin lives in request_private
  location_code text,
  locality text,
  city text,
  state text,
  audience text not null default 'both' check (audience in ('local','online','both')),
  status text not null default 'open' check (status in ('open','closed','awarded','expired','cancelled')),
  quote_count int not null default 0 check (quote_count >= 0),
  max_quotes int not null default 10 check (max_quotes between 1 and 50),
  priority_until timestamptz,
  quote_window_ends_at timestamptz not null,
  accepted_quote_id uuid,
  reference_url text,
  inviting_seller_id uuid references public.sellers(id) on delete set null,
  text_fingerprint text, -- normalized title+description, for duplicate detection
  hidden boolean not null default false,
  closed_at timestamptz,
  window_reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (budget_min_minor is null or budget_max_minor is null or budget_min_minor <= budget_max_minor),
  check (audience = 'online' or location is not null)
);

create table public.request_private (
  request_id uuid primary key references public.requests(id) on delete cascade,
  full_address text,
  buyer_phone text,
  exact_location geography(Point, 4326),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.request_media (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  file_path text not null, -- request-media bucket: {request_id}/...
  type text not null check (type in ('image','video')),
  sort int not null default 0,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- quotes ---------------------------------------------------------------------------
create table public.quotes (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  seller_id uuid not null references public.sellers(id) on delete cascade,
  subtotal_minor bigint not null check (subtotal_minor >= 0),
  tax_minor bigint not null default 0 check (tax_minor >= 0),
  tax_breakdown jsonb not null default '{}'::jsonb,
  delivery_minor bigint not null default 0 check (delivery_minor >= 0),
  total_minor bigint not null check (total_minor >= 0),
  currency char(3) not null,
  offered_brand_model text,
  fields jsonb not null default '{}'::jsonb, -- quote-scope fields from the category field_schema
  delivery_date date,
  warranty text,
  valid_until date,
  notes text check (notes is null or length(notes) <= 4000),
  attachments text[] not null default '{}',
  status text not null default 'sent'
    check (status in ('sent','revised','shortlisted','declined','accepted','withdrawn','expired')),
  revision_count int not null default 0,
  decline_reason text,
  counter_target_minor bigint check (counter_target_minor is null or counter_target_minor >= 0),
  counter_note text,
  countered_at timestamptz,
  shortlisted_at timestamptz,
  accepted_at timestamptz,
  response_mins int,
  billing_source text check (billing_source in
    ('launch_free','early_partner','subscription','free_tier','credit','invited')),
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (total_minor = subtotal_minor + tax_minor + delivery_minor)
);
-- one active quote per (request, seller)
create unique index quotes_one_active_per_seller
  on public.quotes (request_id, seller_id)
  where status in ('sent','revised','shortlisted','accepted');

alter table public.requests
  add constraint requests_accepted_quote_fk foreign key (accepted_quote_id)
  references public.quotes(id) on delete set null deferrable initially deferred;

create table public.quote_line_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  sort int not null default 0,
  description text not null,
  qty numeric(12,3) not null check (qty > 0),
  unit_price_minor bigint not null check (unit_price_minor >= 0),
  tax_rate_bp int not null default 0 check (tax_rate_bp between 0 and 10000),
  hsn_sac text,
  line_total_minor bigint not null,
  tax_minor bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quote_revisions (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quote_templates (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.sellers(id) on delete cascade,
  name text not null,
  category_id bigint references public.categories(id) on delete set null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (seller_id, name)
);

create table public.lead_states (
  seller_id uuid not null references public.sellers(id) on delete cascade,
  request_id uuid not null references public.requests(id) on delete cascade,
  seen_at timestamptz,
  dismissed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (seller_id, request_id)
);

-- chat -----------------------------------------------------------------------------
create table public.chats (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.sellers(id) on delete cascade,
  last_message_at timestamptz,
  last_message_preview text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (request_id, seller_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  type text not null default 'text' check (type in ('text','image','quote_card','system')),
  body text check (body is null or length(body) <= 4000),
  attachment_path text, -- chat-media bucket: {chat_id}/...
  quote_id uuid references public.quotes(id) on delete set null,
  contains_contact boolean not null default false,
  hidden boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (type <> 'text' or body is not null),
  check (type <> 'image' or attachment_path is not null)
);

-- orders -----------------------------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete restrict,
  quote_id uuid not null unique references public.quotes(id) on delete restrict,
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  seller_id uuid not null references public.sellers(id) on delete restrict,
  status text not null default 'accepted'
    check (status in ('accepted','scheduled','dispatched','delivered','completed','cancelled')),
  total_minor bigint not null,
  currency char(3) not null,
  payment_method text check (payment_method in ('cash','upi','card','bank_transfer','zelle','seller_link','other')),
  payment_amount_minor bigint check (payment_amount_minor is null or payment_amount_minor >= 0),
  payment_recorded_at timestamptz,
  scheduled_for timestamptz,
  completed_at timestamptz,
  cancelled_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  at timestamptz not null default now(),
  actor_id uuid references public.profiles(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- reviews ------------------------------------------------------------------------------
create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  from_id uuid references public.profiles(id) on delete set null,
  to_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('buyer_to_seller','seller_to_buyer')),
  stars int not null check (stars between 1 and 5),
  tags text[] not null default '{}',
  text text check (text is null or length(text) <= 2000),
  photos text[] not null default '{}',
  seller_reply text check (seller_reply is null or length(seller_reply) <= 1000),
  seller_replied_at timestamptz,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, role)
);

-- reports -------------------------------------------------------------------------------
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.profiles(id) on delete set null,
  target_type text not null check (target_type in ('request','quote','message','review','seller','user')),
  target_id uuid not null,
  reason text not null check (reason in ('spam','fraud','abusive','inappropriate','prohibited_item','fake','other')),
  details text,
  status text not null default 'open' check (status in ('open','actioned','dismissed')),
  resolved_by uuid references public.profiles(id) on delete set null,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reporter_id, target_type, target_id)
);

-- notifications -------------------------------------------------------------------------
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}'::jsonb, -- {title, body, route, request_id, quote_id, ...}
  read_at timestamptz,
  push_status text not null default 'queued'
    check (push_status in ('queued','sending','sent','skipped','failed','none')),
  push_after timestamptz not null default now(),
  digest_key text, -- notifications with the same digest_key are merged into one push
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- consents -------------------------------------------------------------------------------
create table public.consents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  document text not null check (document in ('terms','privacy','marketing','analytics','whatsapp','seller_terms')),
  version text not null,
  granted boolean not null default true,
  accepted_at timestamptz not null default now(),
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- updated_at triggers + RLS on every table ---------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'profiles','addresses','device_tokens','blocks','postal_codes','cities','categories',
    'category_keywords','sellers','seller_contacts','seller_categories','seller_documents',
    'seller_licences','entitlements','billing_events','requests','request_private',
    'request_media','quotes','quote_line_items','quote_revisions','quote_templates',
    'lead_states','chats','messages','orders','order_events','reviews','reports',
    'notifications','consents']
  loop
    perform private.add_updated_at_trigger(('public.' || t)::regclass);
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;
